export default {
	OK: 'OK',
	CREATED: 'CREATED',
	NO_CONTENT: 'NO_CONTENT',
	BAD_REQUEST: 'BAD_REQUEST',
	UNAUTHORIZED: 'UNAUTHORIZED',
	FORBIDDEN: 'FORBIDDEN',
	NOT_FOUND: 'NOT_FOUND',
	CONFLICT: 'CONFLICT',
	GONE: 'GONE',
	INTERNAL_SERVER: 'INTERNAL_SERVER',
	BAD_GATEWAY: 'BAD_GATEWAY',
};
